from __future__ import annotations

from typing import Any


ACCEPTED_STAGE_CASES: tuple[dict[str, Any], ...] = (
    {
        "name": "chat_response",
        "stage": "chat_response",
        "payload": {
            "status_schema_version": "agentic_v1",
            "reason_code": "not_applicable",
            "reason_short_chars": 18,
            "reason_short_included": False,
        },
    },
    {
        "name": "stream",
        "stage": "llm_call",
        "payload": {
            "status_schema_version": "agentic_v1",
            "mode": "stream",
            "timeout_s": 42,
            "response_chars": 7,
            "stream_chunks": 2,
            "stream_terminal": "done",
            "provider_caller": "llm",
            "provider_title": "FridaDev/LLM",
            "provider_model": "openrouter/runtime-main-model",
            "provider_generation_id": "generation_synthetic",
            "model": "openrouter/runtime-main-model",
        },
    },
    {
        "name": "arbiter",
        "stage": "arbiter",
        "payload": {
            "status_schema_version": "agentic_v1",
            "raw_candidates": 4,
            "kept_candidates": 2,
            "rejected_candidates": 2,
            "mode": "arbiter",
            "model": "openrouter/test-model",
            "decision_source": "fallback",
            "fallback_used": True,
            "fallback_decisions": 1,
            "rejection_reason_code_counts": {"invalid_verdict": 2},
        },
    },
    {
        "name": "memory",
        "stage": "memory_retrieve",
        "payload": {
            "status_schema_version": "agentic_v1",
            "retrieval_status": "ok",
            "reason_code": "memory_retrieved",
            "top_k_requested": 5,
            "retrieved_count": 2,
            "context_hint_count": 1,
            "prompt_injected_count": 1,
            "raw_content_included": False,
        },
    },
    {
        "name": "identity",
        "stage": "identity_write",
        "payload": {
            "status_schema_version": "agentic_v1",
            "target_side": "user",
            "write_effect": "legacy_diagnostic_write",
            "observed_count": 1,
            "retained_count": 1,
            "actions_count": {
                "add": 1,
                "update": 0,
                "override": 0,
                "reject": 0,
                "defer": 0,
            },
            "raw_content_included": False,
        },
    },
    {
        "name": "web",
        "stage": "web_search",
        "payload": {
            "status_schema_version": "agentic_v1",
            "enabled": True,
            "status": "ok",
            "reason_code": "web_context_ready",
            "query_preview": "",
            "query_present": True,
            "query_chars": 20,
            "query_hash_included": False,
            "results_count": 1,
            "context_injected": True,
            "source_material_summary": [
                {
                    "rank": 1,
                    "source_domain": "synthetic.invalid",
                    "source_origin": "search_result",
                    "is_primary_source": False,
                    "used_in_prompt": True,
                    "used_content_kind": "crawl_markdown",
                    "crawl_status": "success",
                    "content_chars": 48,
                    "truncated": False,
                    "url_present": True,
                    "url_chars": 32,
                    "url_included": False,
                }
            ],
        },
    },
    {
        "name": "agenda",
        "stage": "agenda",
        "payload": {
            "schema_version": "frida_agenda_lot6_pending_v1",
            "status_schema_version": "agentic_v1",
            "status": "active_ready",
            "reason_code": "agenda_agent_active_validated",
            "product_method": "find_next_matching_event",
            "caldav_access": True,
            "nextcloud_access": True,
            "secret_access": True,
            "mutation_attempted": False,
            "final_response_override": True,
            "content_free": True,
        },
    },
    {
        "name": "biblio",
        "stage": "biblio",
        "payload": {
            "schema_version": "1",
            "status_schema_version": "agentic_v1",
            "module_key": "biblio",
            "source_kind": "biblio_native_catalogue",
            "status": "disabled",
            "reason_code": "biblio_toggle_disabled",
            "enabled": False,
            "used": False,
            "reason_code_counts": {"biblio_toggle_disabled": 1},
            "content_free": True,
        },
    },
    {
        "name": "stimmung",
        "stage": "stimmung_agent",
        "payload": {
            "status_schema_version": "agentic_v1",
            "present": True,
            "dominant_tone": "neutralite",
            "tones_count": 1,
            "tones": [{"tone": "neutralite", "strength": 3}],
            "confidence": 0.5,
            "decision_source": "fallback",
            "model": "openai/gpt-5.4-mini",
        },
    },
    {
        "name": "manifest",
        "stage": "main_payload_manifest",
        "payload": {
            "schema_version": "main_payload_manifest_v1",
            "status_schema_version": "agentic_v1",
            "scope": "main_chat",
            "messages": [
                {
                    "index": 0,
                    "provider_role": "user",
                    "logical_roles": ["user_turn"],
                    "origin": "current_user_turn",
                    "origin_stage": "final_user_turn",
                    "content_present": True,
                    "content_chars": 48,
                    "content_parts_count": 1,
                    "text_part_count": 1,
                    "file_part_count": 0,
                    "image_part_count": 0,
                    "estimated_tokens": 12,
                    "excluded": False,
                    "exclusion_reason_code": "",
                    "raw_content_included": False,
                }
            ],
            "runtime_settings": {
                "provider_family": "openrouter",
                "model": "openai/gpt-5.4-mini",
                "temperature_present": True,
                "top_p_present": True,
                "max_tokens": 512,
                "stream_requested": False,
            },
            "raw_flags": {
                "raw_prompt_included": False,
                "raw_message_included": False,
                "raw_content_included": False,
                "raw_lane_content_included": False,
                "raw_capsule_content_included": False,
                "raw_provider_payload_included": False,
                "raw_secret_included": False,
            },
        },
    },
)
