"""Document structure primitives for Frida Biblio."""

from .manifest import (
    Anchor,
    CanonicalReference,
    ContentRole,
    DocumentManifest,
    Interval,
    LibraryDocument,
    ManifestValidationResult,
    SectionNode,
    TextUnit,
    Work,
    STATUS_INVALID,
    STATUS_VALID,
    STATUS_VALID_WITH_WARNINGS,
    language_signal,
    build_document_manifest,
    build_manifest_baseline_payload,
    validate_document_manifest,
)

__all__ = [
    "Anchor",
    "CanonicalReference",
    "ContentRole",
    "DocumentManifest",
    "Interval",
    "LibraryDocument",
    "ManifestValidationResult",
    "SectionNode",
    "TextUnit",
    "Work",
    "STATUS_INVALID",
    "STATUS_VALID",
    "STATUS_VALID_WITH_WARNINGS",
    "language_signal",
    "build_document_manifest",
    "build_manifest_baseline_payload",
    "validate_document_manifest",
]
