(() => {
  const sections = [
    {
      key: "main_model",
      title: "Modele principal",
      description: "Provider principal, routage, titres OpenRouter et echantillonnage global.",
    },
    {
      key: "arbiter_model",
      title: "Modele arbitre",
      description: "Decision memoire, timeout et reglages propres a l'arbitre.",
    },
    {
      key: "summary_model",
      title: "Modele resumeur",
      description: "Synthese conversationnelle et reglages de resume.",
    },
    {
      key: "stimmung_agent_model",
      title: "Agent Stimmung",
      description: "Agent LLM affectif amont, avec primaire/repli, echantillonnage et timeout propres.",
    },
    {
      key: "validation_agent_model",
      title: "Agent de validation",
      description: "Agent LLM aval de relecture, avec primaire/repli, echantillonnage, timeout et budget de sortie.",
    },
    {
      key: "embedding",
      title: "Embeddings",
      description: "Endpoint, modele, dimensions et top-k pour la memoire vectorielle.",
    },
    {
      key: "database",
      title: "Base de donnees",
      description: "Lecture de la config V1 cote base, avec bootstrap externe maintenu.",
    },
    {
      key: "services",
      title: "Services externes",
      description: "SearXNG, Crawl4AI et surfaces d'appel reseau.",
    },
    {
      key: "resources",
      title: "Ressources",
      description: "Chemins identite et ressources runtime externes au depot logique.",
    },
  ];
  const mainModelFieldSpecs = [
    {
      key: "base_url",
      label: "Base URL",
      hint: "Endpoint provider principal.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "model",
      label: "Modele",
      hint: "Routage principal utilise par le chat.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "referer",
      label: "Referer",
      hint: "Fallback legacy partage si aucun referer de composant n'est renseigne.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "referer_llm",
      label: "Referer LLM",
      hint: "Referer OpenRouter nominal du flux principal.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "referer_arbiter",
      label: "Referer arbitre",
      hint: "Referer OpenRouter nominal du flux arbitre.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "referer_identity_extractor",
      label: "Referer extracteur d'identite",
      hint: "Referer OpenRouter nominal du flux d'extraction d'identite.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "referer_resumer",
      label: "Referer resumeur",
      hint: "Referer OpenRouter nominal du flux resume.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "referer_stimmung_agent",
      label: "Referer Stimmung",
      hint: "Referer OpenRouter nominal du flux Stimmung.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "referer_validation_agent",
      label: "Referer validation",
      hint: "Referer OpenRouter nominal du flux de validation.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "app_name",
      label: "App name",
      hint: "Nom expose cote provider.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "title_llm",
      label: "Titre LLM",
      hint: "Titre du flux principal cote provider.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "title_arbiter",
      label: "Titre arbitre",
      hint: "Titre du flux arbitre cote provider.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "title_identity_extractor",
      label: "Titre extracteur d'identite",
      hint: "Titre OpenRouter du flux d'extraction d'identite.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "title_resumer",
      label: "Titre resumeur",
      hint: "Titre du flux resume cote provider.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "title_stimmung_agent",
      label: "Titre Stimmung",
      hint: "Titre OpenRouter du flux Stimmung.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "title_validation_agent",
      label: "Titre validation",
      hint: "Titre OpenRouter du flux de validation.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "temperature",
      label: "Temperature",
      hint: "Echantillonnage global du modele principal.",
      inputType: "number",
      step: "0.1",
      min: "0",
      max: "2",
      autocomplete: "off",
    },
    {
      key: "top_p",
      label: "Top p",
      hint: "Coupe nucleus globale du modele principal.",
      inputType: "number",
      step: "0.05",
      min: "0.01",
      max: "1",
      autocomplete: "off",
    },
    {
      key: "response_max_tokens",
      label: "Max tokens reponse",
      hint: "Budget de generation par defaut envoye au modele principal.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
  ];
  const mainModelCheckFieldMap = {
    api_key_runtime: "api_key",
  };
  const arbiterModelFieldSpecs = [
    {
      key: "model",
      label: "Modele",
      hint: "Modele utilise pour la decision memoire.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "temperature",
      label: "Temperature",
      hint: "Echantillonnage propre a l'arbitre.",
      inputType: "number",
      step: "0.1",
      min: "0",
      max: "2",
      autocomplete: "off",
    },
    {
      key: "top_p",
      label: "Top p",
      hint: "Coupe nucleus de l'arbitre.",
      inputType: "number",
      step: "0.05",
      min: "0.01",
      max: "1",
      autocomplete: "off",
    },
    {
      key: "timeout_s",
      label: "Timeout",
      hint: "Timeout applique aux appels arbitre.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
  ];
  const summaryModelFieldSpecs = [
    {
      key: "model",
      label: "Modele",
      hint: "Modele utilise pour la synthese conversationnelle.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "temperature",
      label: "Temperature",
      hint: "Echantillonnage propre au resumeur.",
      inputType: "number",
      step: "0.1",
      min: "0",
      max: "2",
      autocomplete: "off",
    },
    {
      key: "top_p",
      label: "Top p",
      hint: "Coupe nucleus du resumeur.",
      inputType: "number",
      step: "0.05",
      min: "0.01",
      max: "1",
      autocomplete: "off",
    },
  ];
  const stimmungAgentModelFieldSpecs = [
    {
      key: "primary_model",
      label: "Modele primaire",
      hint: "Modele principal de l'agent Stimmung.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "fallback_model",
      label: "Modele repli",
      hint: "Modele de secours de l'agent Stimmung.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "timeout_s",
      label: "Timeout",
      hint: "Timeout applique aux appels Stimmung.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
    {
      key: "temperature",
      label: "Temperature",
      hint: "Echantillonnage propre a l'agent Stimmung.",
      inputType: "number",
      step: "0.1",
      min: "0",
      max: "2",
      autocomplete: "off",
    },
    {
      key: "top_p",
      label: "Top p",
      hint: "Coupe nucleus propre a l'agent Stimmung.",
      inputType: "number",
      step: "0.05",
      min: "0.01",
      max: "1",
      autocomplete: "off",
    },
    {
      key: "max_tokens",
      label: "Max tokens",
      hint: "Budget de sortie envoye au modele Stimmung.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
  ];
  const stimmungAgentModelCheckFieldMap = {
    shared_transport_runtime: "primary_model",
  };
  const validationAgentModelFieldSpecs = [
    {
      key: "primary_model",
      label: "Modele primaire",
      hint: "Modele principal de l'agent de validation.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "fallback_model",
      label: "Modele repli",
      hint: "Modele de secours de l'agent de validation.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "timeout_s",
      label: "Timeout",
      hint: "Timeout applique aux appels de validation.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
    {
      key: "temperature",
      label: "Temperature",
      hint: "Echantillonnage propre a l'agent de validation.",
      inputType: "number",
      step: "0.1",
      min: "0",
      max: "2",
      autocomplete: "off",
    },
    {
      key: "top_p",
      label: "Top p",
      hint: "Coupe nucleus propre a l'agent de validation.",
      inputType: "number",
      step: "0.05",
      min: "0.01",
      max: "1",
      autocomplete: "off",
    },
    {
      key: "max_tokens",
      label: "Max tokens",
      hint: "Budget de sortie envoye au modele de validation, borne contractuelle max 80.",
      inputType: "number",
      step: "1",
      min: "1",
      max: "80",
      autocomplete: "off",
    },
  ];
  const validationAgentModelCheckFieldMap = {
    shared_transport_runtime: "primary_model",
  };
  const embeddingFieldSpecs = [
    {
      key: "endpoint",
      label: "Endpoint",
      hint: "Service HTTP d'embedding.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "model",
      label: "Modele",
      hint: "Modele actif du service d'embedding.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "dimensions",
      label: "Dimensions",
      hint: "Dimension vectorielle attendue par la base.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
    {
      key: "top_k",
      label: "Top k",
      hint: "Nombre de voisins retournes lors de la recherche.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
  ];
  const embeddingCheckFieldMap = {
    token_runtime: "token",
  };
  const databaseFieldSpecs = [
    {
      key: "backend",
      label: "Backend",
      hint: "Backend runtime supporte pendant cette phase.",
      inputType: "text",
      autocomplete: "off",
    },
  ];
  const databaseCheckFieldMap = {
    dsn_transition: "dsn",
  };
  const servicesFieldSpecs = [
    {
      key: "searxng_url",
      label: "SearXNG URL",
      hint: "Endpoint de recherche federative.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "searxng_results",
      label: "SearXNG results",
      hint: "Nombre de resultats pris en compte cote recherche.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
    {
      key: "crawl4ai_url",
      label: "Crawl4AI URL",
      hint: "Endpoint du service de crawl.",
      inputType: "url",
      autocomplete: "url",
    },
    {
      key: "crawl4ai_top_n",
      label: "Crawl4AI top n",
      hint: "Nombre de pages retenues dans le contexte.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
    {
      key: "crawl4ai_max_chars",
      label: "Crawl4AI max chars",
      hint: "Budget maximal de caracteres injectes en contexte.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
    {
      key: "crawl4ai_explicit_url_max_chars",
      label: "Crawl4AI explicit URL max chars",
      hint: "Budget maximal de caracteres injectes pour une URL explicite utilisateur.",
      inputType: "number",
      step: "1",
      min: "1",
      autocomplete: "off",
    },
  ];
  const servicesCheckFieldMap = {
    crawl4ai_token_runtime: "crawl4ai_token",
  };
  const resourcesFieldSpecs = [
    {
      key: "llm_identity_path",
      label: "LLM static resource path",
      hint: "Reference de ressource du statique actif cote modele. Le contenu s'edite depuis Hermeneutic admin.",
      inputType: "text",
      autocomplete: "off",
    },
    {
      key: "user_identity_path",
      label: "User static resource path",
      hint: "Reference de ressource du statique actif cote utilisateur. Le contenu s'edite depuis Hermeneutic admin.",
      inputType: "text",
      autocomplete: "off",
    },
  ];

  window.FridaAdminSettingsCatalog = Object.freeze({
    sections,
    mainModelFieldSpecs,
    mainModelCheckFieldMap,
    arbiterModelFieldSpecs,
    summaryModelFieldSpecs,
    stimmungAgentModelFieldSpecs,
    stimmungAgentModelCheckFieldMap,
    validationAgentModelFieldSpecs,
    validationAgentModelCheckFieldMap,
    embeddingFieldSpecs,
    embeddingCheckFieldMap,
    databaseFieldSpecs,
    databaseCheckFieldMap,
    servicesFieldSpecs,
    servicesCheckFieldMap,
    resourcesFieldSpecs,
  });
})();
